name: segformer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu121
    - torchvision --index-url https://download.pytorch.org/whl/cu121
    - mmcv-full
    - timm
    - numpy
    - Pillow
    - scipy
    - matplotlib
    - opencv-python
    - albumentations
    - prettytable
    - terminaltables
    - yapf
    - addict
